serviceName: "products"
srv_discovery:
  url: "http://localhost:50030"

server:
  mode: "dev"
  port: 50060
  scheme: "http"
  domain: "localhost"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  database: "par_pro_products_db"

testDB:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  database: "par_pro_products_db_test"

redis:
  addr: "localhost:6379"
  pass: ""

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "localhost:6831"