version: 3

tasks:
  app:
    desc: Run app
    cmds:
      - "go run cmd/main.go"

  pb:
    desc: Gen Proto file
    cmds:
      - "protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative api/pb/products.proto"

  mocks:
    desc: Generate mocks
    cmds:
      - mockgen -source="./internal/hdl/interfaces.go" -destination="mocks/mock_ctrl.go" -package=mocks
      - mockgen -source="./internal/ctrl/ctrl.go" -destination="mocks/mock_repos.go" -package=mocks
      - mockgen -source="./internal/ctrl/sso/sso.go" -destination="mocks/mock_sso.go" -package=mocks


  t:
    desc: Run tests
    cmds:
      - "task t-hdl"
      - "task t-ctrl"
      - "task t-repo"

  t-hdl:
    desc: Test handlers
    cmds:
      - "go test ./internal/hdl/http"
      - "go test -coverprofile=cov_http.out ./internal/hdl/http && go tool cover -func=cov_http.out"
      - "go test -coverprofile=cov_http.out ./internal/hdl/http && go tool cover -html=cov_http.out"
      - "go test ./internal/hdl/grpc"
      - "go test -coverprofile=cov_grpc.out ./internal/hdl/grpc && go tool cover -func=cov_grpc.out"
      - "go test -coverprofile=cov_grpc.out ./internal/hdl/grpc && go tool cover -html=cov_grpc.out"

  t-grpc:
    desc: Test grpc handlers
    cmds:
      - "go test ./internal/hdl/grpc"
      - "go test -coverprofile=cov_grpc.out ./internal/hdl/grpc && go tool cover -func=cov_grpc.out"

  t-mid:
    desc: Test middlewares
    cmds:
      - "go test ./internal/hdl/http/middleware"

  t-ctrl:
    desc: Run ctrl tests
    cmds:
      - "go test ./internal/ctrl"
      - "go test -coverprofile=cov_ctrl.out ./internal/ctrl && go tool cover -func=cov_ctrl.out"
      - "go test -coverprofile=cov_ctrl.out ./internal/ctrl && go tool cover -html=cov_ctrl.out"

  t-repo:
    desc: Run repo tests
    cmds:
      - "go test ./internal/repo/db"
      - "go test -coverprofile=cov_repo.out ./internal/repo/db && go tool cover -func=cov_repo.out"
      #- "go test -coverprofile=cov_repo.out ./internal/repo/db && go tool cover -html=cov_repo.out"
